id: PF3AD34BE
initial_creation_type: input
source_metadata:
  title: Jampal Dewe Nyima Series
  language: en
  description: 'Texts by and about Khenchen Jampal Dewe Nyima (''jam dpal bde ba''i
    nyi ma) alias Gyurme Pendé Özer, the younger brother of Tertön Rangrik Dorje and
    teacher of Dudjom Rinpoche:'
  volume:
    c596009cb43842738012a53a6ba12fbc:
      title: Prayer to the Lineage of Lumorab
      parent: Lineage Prayers
    ef54d31418184e15a5004df5ae1c53a0:
      title: The Meaning of the Six Syllables of the King of Vidyā-Mantras, the Heroic
        Lord Mañjuśrī
      parent: Mantra
created_at: '2022-02-28T23:33:30.498497'
last_modified_at: '2022-02-28T23:33:30.498503'
